{
 "title": "Advertise Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top 5 Advertised Brands",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT brand, COUNT(*) AS interactions\r\nFROM car_ad INNER JOIN ad_interaction ON car_ad.id = ad_interaction.ad_id\r\nGROUP BY brand\r\nORDER BY interactions DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "Top 5 Most Viewed Ads",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ad_id, COUNT(*) AS view_count\r\nFROM ad_interaction \r\nWHERE type = FALSE  -- FALSE for views\r\nGROUP BY ad_id\r\nORDER BY view_count DESC\r\nLIMIT 5;\r\n"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "stat",
   "description": "Number of unique session",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(DISTINCT session_id) AS session_count \r\nFROM ad_interaction;\r\n"
    }
   ]
  },
  {
   "title": "Top 5 Most Clicked Ads",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT ad_id, COUNT(*) AS click_count\r\nFROM ad_interaction \r\nWHERE type = TRUE  -- TRUE for clicks\r\nGROUP BY ad_id\r\nORDER BY click_count DESC\r\nLIMIT 5;\r\n"
    }
   ]
  }
 ]
}